import Footer from "./footer.tsx"
import Header from './header.tsx'
import { Metadata } from "next"

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "First Next.js project",
    template: "%s | Henry Nuñez"
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
       <body>
        <Header/>
        {children}
        <Footer/>
       </body>
       
    </html>
  )
}
